if has('vim_starting')
 if &compatible
   set nocompatible   " Be iMproved
 endif

 " Required:
 set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

" Required:
call neobundle#begin(expand('~/.vim/bundle/'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

" --- Bundles! ---
{%- for bundle in bundles %}
NeoBundle '{{ bundle }}'
{%- endfor %}
" --- /Bundles! ---

call neobundle#end()

" Vim5 and later versions support syntax highlighting.
" This enables syntax highlighting by default.
syntax enable

" set colors
set t_Co=256
set background={{ background }}
colorscheme {{ colorscheme }}

" jump to the last position when
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" load indentation rules and plugins
" according to the detected filetype.
filetype plugin indent on

let mapleader="{{ mapleader }}"

set showcmd    " Show (partial) command in status line.
set showmatch    " Show matching brackets.
set ignorecase   " Do case insensitive matching
set smartcase    " Do smart case matching
set incsearch    " Incremental search
set autowrite    " Automatically save before commands like :next and :make
set hidden   " Hide buffers when they are abandoned
set mouse=a    " Enable mouse usage (all modes)

" set tab / spaces
set tabstop=8
set expandtab
set softtabstop={{ tabwidth }}
set shiftwidth={{ tabwidth }}

{{ vimrc | replace('\\n', '\n') }}

" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck
